[package]
name = "windfire"
version = "0.4.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.48", features = ["derive"] }
reqwest = { version = "0.12.23", features = ["socks"] }
serde = { version = "1.0.228", features = ["derive"] }
tokio = { version = "1.47.1", features = ["full"] }
regex = "1.11.3"
base64 = "0.22.1"
murmur3 = "0.5.2"
serde_json = "1.0.145"
once_cell = "1.21.3"
futures = "0.3.31"
csv = "1.3.1"
url = "2.5.7"

[profile.release]
lto = true # 启用链路时间优化
opt-level = "z"  # 针对规模进行优化
codegen-units = 1 # 减少并行代码生成单元以提高优化
debug = false # 禁用调试信息生成，从而减小最终二进制文件的大小
strip = true # 删除编译生成的二进制文件中的调试信息和符号
panic = "abort"
